language: node_js
node_js:
- 9
notifications:
  email: false
script:
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build/modern
  on:
    branch: master
