language: node_js
node_js:
- 9
notifications:
  email: false
  slack:
    secure: tfMpJBcyjxvUAe4sQ9JkgxFscq3GOgBS7hDx46Z948Q2z/5GTP4HxiL3gWesJaxOE8xhCleS4CdTlHYQP2xwQdV/Pwi7mAVPm7I5KsjqPTT+XsBwXsCsRMdgRHpIWLY6pNV8CaLDMFiShNXjAUK6Wut/mQmL2113SuRsu+QS2SRMq+UzvyAfAm3KK+rYVfKW5dSDsbeX0xv1zR9Ic6kYzmj2S1M4UiRHcrmWQMIfn2iMau4aG8/WlkY7dIQCiRiiUukOHxIkDRdtwtrxtFhN10+U3f17ftfhVDScoIaqNMIBV3dqsCXzXywOmesSkc6eDhJMieO0KDK66k/jpLp+1J4mYJPkjisnpqk9GRfob/JkIUbn3pdt5mTmHhbkWs1Yf1wDxEGHDMEtATnKxaMZx/FKD+FKwfr+IZ8YH9qw3tVvFirftzhfhEOE8giZ5tld3bJ2sIiHe9Lc13OLfrtSK9aEzml3S8l4a51Li0P35CRDmOKg20FGKsFQ7E8xOcxxxWevOf4jdZll+aY9QQ9kslXdZ95bA3zmfZfNP107KdVDVpec6sxCjpK4KH60zp9KeyUV/jpqmfMWEsqkr4h4cMxGcQ5hhps84qHvN2LmUm8gAVcLBRo+pr3u8NEDB6pk33BExs1Wx8/f3sb2rPxTP7Ivc0D1BJnjqw4b9vOkCCM=
script:
- npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: "$github_token"
  local_dir: build/modern
  on:
    branch: master
